name: Update FB posts JSON

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch Facebook posts
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
        run: python fetch_posts.py

      - name: Debug – show token available
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [ -z "${GH_PAT}" ]; then
            echo "❌ GH_PAT is NOT set"
            exit 1
          else
            echo "✅ GH_PAT is present"
          fi

      - name: Commit posts.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add posts.json
          git commit -m "Update FB posts" || echo "Nothing to commit"

      - name: Push using secure GitHub Action
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_PAT }}

